version: '3'
services:
  app:
    container_name: docker-node-redis-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
      - '6379:6379'
    links:
      - mongo
      - redis-server
  mongo:
      container_name: mongo
      image: mongo
      ports:
        - '27017:27017'
  redis-server:      
      container_name: redis
      image: redis
      
  